<?php
define("URL","http://prod.api.pvp.net/api/");
define("URLPOSTFIX","lol/");
define("APIKEY","ee9af537-a4f1-4a7a-9e7c-7ca19e4aa7a3");
define("KEYPREFIX","?api_key=");
define("LEAGUE","league/");
define("CHAMPION","champion/");
define("BYSUMMONER","by-summoner/");
define("SUMMONER","summoner/");
define("BYNAME","by-name");
define("NAME","name");
define("STATS","stats/");
define("SUMMARY","summary");
define("RANKED","ranked");
define("RUNES","runes");
define("MASTERIES","masteries");
define("TEAM","team/");
define("RECENT","recent");
define("GAME","game");
define("SLASH","/");
?>
